<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreImageRequest extends MainRequest
{

    public function rules(): array
    {
        return [
            'images' => 'array | required',
            'images.*.supplier_id' => 'nullable | integer',
            'images.*.product_id' => 'nullable |  integer',
            'images.*.name' => 'string | nullable',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
