<?php

namespace App\Http\Requests;


class UpdateCategoryRequest extends MainRequest
{

    public function rules(): array
    {
        return [
            'parent_id'=>'nullable | integer',
            'name'=>'string | required',
            'description'=>'string | nullable',
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
